language: node_js
node_js:
  - "0.11"
branches:
  only:
  - master
before_install: npm install -g grunt-cli
install: npm install
before_script:
  - git config --global user.email "edwardtoday@gmail.com"
  - git config --global user.name "Travis-CI"
  - git config --global credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
script: grunt gitbook
after_success: grunt gh-pages:travis
env:
  global:
  - secure: "Ah9GCLuY/OpemhsywbSGYyDT18mQ4mHHhE5wYF/GBthLnqFIUU0GSS2BbVTWeaKpIkemOQz5VnRfLKp+4XKmw7aPA5H0lc4Aolk0M+tKXE0NJudOgumnQq1Tdx9PFtOy3pDBi2t39bMxdhoQxeAKrau8PkyZb75TMiDRvDl8z2E="
