language: ruby
rvm:
  - 2.0.0
env:
  - "git-scribe-qp"
before_install:
  - gem --version
  - sudo apt-get install asciidoc source-highlight fop
  - wget http://kindlegen.s3.amazonaws.com/kindlegen_linux_2.6_i386_v2_9.tar.gz
  - tar -zxvf kindlegen_linux_2.6_i386_v2_9.tar.gz kindlegen
  - sudo mv kindlegen /usr/local/bin/
  - rm kindlegen_linux_2.6_i386_v2_9.tar.gz kindlegen
  - git scribe check
script: git scribe gen all

