language: ruby
cache:
- bundler
- apt
rvm:
- 2.0.0
branches:
  only:
  - master
before_install:
- sudo apt-get install asciidoc source-highlight fop
- sudo apt-get install ttf-wqy-zenhei ttf-wqy-microhei ttf-liberation
- wget http://kindlegen.s3.amazonaws.com/kindlegen_linux_2.6_i386_v2_9.tar.gz
- tar -zxvf kindlegen_linux_2.6_i386_v2_9.tar.gz kindlegen
- sudo mv kindlegen /usr/local/bin/
- rm kindlegen_linux_2.6_i386_v2_9.tar.gz
- sudo pip install Pygments
before_script:
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
bundler_args: --binstubs
script: sh ci.sh
env:
  global:
  - GH_REPO="edwardtoday/sansi-book"
  - GH_BRANCH="gh-pages"
  - secure: "Ah9GCLuY/OpemhsywbSGYyDT18mQ4mHHhE5wYF/GBthLnqFIUU0GSS2BbVTWeaKpIkemOQz5VnRfLKp+4XKmw7aPA5H0lc4Aolk0M+tKXE0NJudOgumnQq1Tdx9PFtOy3pDBi2t39bMxdhoQxeAKrau8PkyZb75TMiDRvDl8z2E="
