language: ruby
cache:
- bundler
- apt
rvm:
- 2.0.0
branches:
  only:
  - master
before_install:
- gem --version
- sudo apt-get install asciidoc source-highlight fop
- wget http://kindlegen.s3.amazonaws.com/kindlegen_linux_2.6_i386_v2_9.tar.gz
- tar -zxvf kindlegen_linux_2.6_i386_v2_9.tar.gz kindlegen
- sudo mv kindlegen /usr/local/bin/
- rm kindlegen_linux_2.6_i386_v2_9.tar.gz
- gem install -V git-scribe-qp
- sudo pip install Pygments
- git scribe check
before_script:
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
script: sh ci.sh
env:
  global:
  - GH_REPO="edwardtoday/sansi-book"
  - GH_BRANCH="gh-pages"
  - secure: "ioF1ED4CQb/GzxwVGh2GpfdZTS6muqmgvNYvBcT2Qa2yg5W+4Yq9BbtOqv9Yww4S6mQmIPwLfWppP7cP/Z4PXMaviuiMLHIvKedsKn8797ZaZJQVNUwrZF4Kl4iH+uMz9hHd1ELzqfpay3JKDVj+z+eAWhlZM3jW8ZnEzyCMAjo="
