language: node_js
node_js:
  - "0.10"
branches:
  only:
  - master
before_install: npm install -g grunt-cli
before_script:
  - export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
install: npm install
before_script: grunt gitbook
script: grunt publish
env:
  global:
  - GH_REPO="edwardtoday/sansi-book"
  - GH_BRANCH="gh-pages"
  - secure: "Ah9GCLuY/OpemhsywbSGYyDT18mQ4mHHhE5wYF/GBthLnqFIUU0GSS2BbVTWeaKpIkemOQz5VnRfLKp+4XKmw7aPA5H0lc4Aolk0M+tKXE0NJudOgumnQq1Tdx9PFtOy3pDBi2t39bMxdhoQxeAKrau8PkyZb75TMiDRvDl8z2E="
